import pandas as pd

from _bootstrap import DATA


def load_daily(name: str) -> pd.DataFrame:
    """Load a generated daily weather set (gzipped CSV, regenerated by step 01)."""
    path = DATA / f"daily_{name}.csv.gz"
    if not path.exists():
        raise FileNotFoundError(f"{path.name} missing - run 01_generate_data.py first")
    df = pd.read_csv(path, compression="gzip")
    df["date"] = pd.to_datetime(df["date"])
    return df
